### ISSUE TITLE
xjsfl.com is shutdown

### ISSUE THREAD

**Issue by cailven** [davestewart/xjsfl#18]
what happening?

**Comment by davestewart** [comment]
Hey, I haven't looked at the site for ages, suspect WordPress / that plugin has not updated itself.

Do you need the site?

I wonder, do people still use xJSFL!?

**Comment by sp-nicola-sirago** [comment]
you won’t believe how many people are still using it.

Il giorno ven 17 lug 2020 alle 21:37 Dave Stewart <notifications@github.com>
ha scritto:

**Comment by davestewart** [comment]
> you won’t believe how many people are still using it.

Anything above zero would be a surprise!

**Comment by davestewart** [comment]
So getting the site up and running again was pretty easy; just needed to tweak a couple of files.

Clearly, Flash has had its day, and this project just lives on – pretty much ignored by me.

I was considering taking the site down when I get time, but do I need to keep the site up?

**Comment by sp-nicola-sirago** [comment]
thanks for your work, I think xjstl is still useful, maybe you can just
wrap it up the most relevant content in github and shout down the site.
Unfortunately flash has made the history, but its own history is almost
over.

Il giorno sab 18 lug 2020 alle 16:56 Dave Stewart <notifications@github.com>
ha scritto:

**Comment by davestewart** [comment]
If I can keep WP running, I'm happy to do that.

But it looks like the "support" section of the site was written in raw HTML, so making them available would be simple:

- http://xjsfl.com/wp-content/documentation/html/api/

LMK, and I'll get it onto GitHub at least.

**Comment by cailven** [comment]
> Hey, I haven't looked at the site for ages, suspect WordPress / that plugin has not updated itself.
> 
> Do you need the site?
> 
> I wonder, do people still use xJSFL!?

Thanks a lot for recovering the website.I already use jsfl in flash,but just for html5 exporter(not swf file).as you known the flash age has gone,but the adobe animate is also greater animator tools for html5,video and so on.

**Comment by cailven** [comment]
> Flash has had its day,

Flash age has gone.Its right,but I use flash just for the tool,not for swf.exactly,JSFL is running in flash,its can exporter anyform animation data if you want. and it can use any fields programming coding.(include json,c++,python,java as you know).Flash as a tool is great! JSFL is the intermedia code as you know.
