### ISSUE TITLE
I need a little help

### ISSUE THREAD

**Issue by cailven** [davestewart/xjsfl#19]
Thanks for you reopen the API host. 
but this api has gone (404), could you recover it?thanks alot https://xjsfl.vercel.app/support/api/flash/Iterators

**Comment by davestewart** [comment]
Oh dear!

I just checked the site, and there are various broken links, which I have attempted to fix. It should be live now:

- https://xjsfl.vercel.app/support/api/flash/Iterators

Also – annoyingly – it looks like some of the content has not properly exported from the original WordPress site. Luckily this seems only to be some of the tutorial content. I can't remember now if this content was real content or just redirects (as some of the pages were).

Also, I have various archived WP exports, so if if you come across any other issues raise a ticket and I can see what I can do.

:D
